apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - args:
            - bundle
            - exec
            - bin/rails
            - server
            - -b
            - 0.0.0.0
          env:
            - name: DATABASE_URL
              value: postgres://foreman:foreman@db/foreman?pool=5
            - name: DYNFLOW_REDIS_URL
              value: redis://redis-tasks:6379/0
            - name: FOREMAN_DOMAIN
              value: example.com
            - name: FOREMAN_FQDN
              value: foreman.example.com
            - name: FOREMAN_RAILS_CACHE_STORE_TYPE
              value: redis
            - name: FOREMAN_RAILS_CACHE_STORE_URLS
              value: redis://redis-cache:6379/0
            - name: RAILS_ENV
              value: production
            - name: RAILS_MAX_THREADS
              value: "5"
            - name: REDIS_PROVIDER
              value: DYNFLOW_REDIS_URL
          image: quay.io/foreman/foreman:develop
          livenessProbe:
            exec:
              command:
                - nc -z 127.0.0.1 3000 || exit 1
            initialDelaySeconds: 60
            periodSeconds: 300
          name: app
          ports:
            - containerPort: 3000
            - containerPort: 5910
            - containerPort: 5911
            - containerPort: 5912
            - containerPort: 5913
            - containerPort: 5914
            - containerPort: 5915
            - containerPort: 5916
            - containerPort: 5917
            - containerPort: 5918
            - containerPort: 5919
            - containerPort: 5920
            - containerPort: 5921
            - containerPort: 5922
            - containerPort: 5923
            - containerPort: 5924
            - containerPort: 5925
            - containerPort: 5926
            - containerPort: 5927
            - containerPort: 5928
            - containerPort: 5929
            - containerPort: 5930
          resources: {}
      hostname: foreman.example.com
      restartPolicy: Always
status: {}
