apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orchestrator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: orchestrator
    spec:
      containers:
        - args:
            - bundle
            - exec
            - sidekiq
            - -r
            - ./extras/dynflow-sidekiq.rb
            - -c
            - "1"
            - -q
            - dynflow_orchestrator
          env:
            - name: DATABASE_URL
              value: postgres://foreman:foreman@db/foreman?pool=5
            - name: DYNFLOW_REDIS_URL
              value: redis://redis-tasks:6379/0
            - name: FOREMAN_DOMAIN
              value: example.com
            - name: FOREMAN_FQDN
              value: foreman.example.com
            - name: FOREMAN_RAILS_CACHE_STORE_TYPE
              value: redis
            - name: FOREMAN_RAILS_CACHE_STORE_URLS
              value: redis://redis-cache:6379/0
            - name: RAILS_ENV
              value: production
            - name: RAILS_MAX_THREADS
              value: "5"
            - name: REDIS_PROVIDER
              value: DYNFLOW_REDIS_URL
          image: quay.io/foreman/foreman:develop
          livenessProbe:
            exec:
              command:
                - nc -z 127.0.0.1 3000 || exit 1
            initialDelaySeconds: 60
            periodSeconds: 300
          name: orchestrator
          resources: {}
      hostname: orchestrator.example.com
      restartPolicy: Always
status: {}
